// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestCons;

#nullable disable

namespace TestCons.Migrations
{
    [DbContext(typeof(TaxiDbContext))]
    partial class TaxiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestCons.TaxiTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DOLocationID")
                        .HasColumnType("integer");

                    b.Property<int?>("PULocationID")
                        .HasColumnType("integer");

                    b.Property<decimal?>("fare_amount")
                        .HasColumnType("numeric");

                    b.Property<int?>("passenger_count")
                        .HasColumnType("integer");

                    b.Property<string>("store_and_fwd_flag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("tip_amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("tpep_dropoff_datetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("tpep_pickup_datetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("trip_distance")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PULocationID");

                    b.HasIndex("trip_distance");

                    b.HasIndex("tpep_pickup_datetime", "tpep_dropoff_datetime");

                    b.ToTable("TaxiTrips");
                });
#pragma warning restore 612, 618
        }
    }
}
